// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: routine.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_routine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_routine_proto protoreflect.FileDescriptor

const file_routine_proto_rawDesc = "" +
	"\n" +
	"\rroutine.proto\x12\aroutine\"!\n" +
	"\x05Frame\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload2e\n" +
	"\x0eRoutineService\x12%\n" +
	"\x03Req\x12\x0e.routine.Frame\x1a\x0e.routine.Frame\x12,\n" +
	"\x06Stream\x12\x0e.routine.Frame\x1a\x0e.routine.Frame(\x010\x01B\x12Z\x10kernel/grpc;grpcb\x06proto3"

var (
	file_routine_proto_rawDescOnce sync.Once
	file_routine_proto_rawDescData []byte
)

func file_routine_proto_rawDescGZIP() []byte {
	file_routine_proto_rawDescOnce.Do(func() {
		file_routine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routine_proto_rawDesc), len(file_routine_proto_rawDesc)))
	})
	return file_routine_proto_rawDescData
}

var file_routine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_routine_proto_goTypes = []any{
	(*Frame)(nil), // 0: routine.Frame
}
var file_routine_proto_depIdxs = []int32{
	0, // 0: routine.RoutineService.Req:input_type -> routine.Frame
	0, // 1: routine.RoutineService.Stream:input_type -> routine.Frame
	0, // 2: routine.RoutineService.Req:output_type -> routine.Frame
	0, // 3: routine.RoutineService.Stream:output_type -> routine.Frame
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routine_proto_init() }
func file_routine_proto_init() {
	if File_routine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routine_proto_rawDesc), len(file_routine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routine_proto_goTypes,
		DependencyIndexes: file_routine_proto_depIdxs,
		MessageInfos:      file_routine_proto_msgTypes,
	}.Build()
	File_routine_proto = out.File
	file_routine_proto_goTypes = nil
	file_routine_proto_depIdxs = nil
}
