// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: routine.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutineService_Req_FullMethodName    = "/routine.RoutineService/Req"
	RoutineService_Stream_FullMethodName = "/routine.RoutineService/Stream"
)

// RoutineServiceClient is the client API for RoutineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Frame -- wire 上唯一消息类型: payload = 完整事件消息的 JSON 文本
// (平铺 dict: {event, id, req_id, ...业务字段}, 事件字段面见 py 侧
// routine/protocol.py 的事件常量, proto 层不镜像字段----加事件零重生成).
//
// 边界编解码: py json.dumps/loads (C 实现) / Go sonic(JIT) / rs
// serde_json, 各语言内部数据流(map/dict/Value)不变. 相比
// google.protobuf.Struct 少两层 Value 包装反射, wire 体积更小,
// 且跨语言统一 JSON string 单一格式(kernel 对 payload 按需解析).
type RoutineServiceClient interface {
	Req(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*Frame, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type routineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutineServiceClient(cc grpc.ClientConnInterface) RoutineServiceClient {
	return &routineServiceClient{cc}
}

func (c *routineServiceClient) Req(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*Frame, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Frame)
	err := c.cc.Invoke(ctx, RoutineService_Req_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoutineService_ServiceDesc.Streams[0], RoutineService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoutineService_StreamClient = grpc.BidiStreamingClient[Frame, Frame]

// RoutineServiceServer is the server API for RoutineService service.
// All implementations must embed UnimplementedRoutineServiceServer
// for forward compatibility.
//
// Frame -- wire 上唯一消息类型: payload = 完整事件消息的 JSON 文本
// (平铺 dict: {event, id, req_id, ...业务字段}, 事件字段面见 py 侧
// routine/protocol.py 的事件常量, proto 层不镜像字段----加事件零重生成).
//
// 边界编解码: py json.dumps/loads (C 实现) / Go sonic(JIT) / rs
// serde_json, 各语言内部数据流(map/dict/Value)不变. 相比
// google.protobuf.Struct 少两层 Value 包装反射, wire 体积更小,
// 且跨语言统一 JSON string 单一格式(kernel 对 payload 按需解析).
type RoutineServiceServer interface {
	Req(context.Context, *Frame) (*Frame, error)
	Stream(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedRoutineServiceServer()
}

// UnimplementedRoutineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutineServiceServer struct{}

func (UnimplementedRoutineServiceServer) Req(context.Context, *Frame) (*Frame, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Req not implemented")
}
func (UnimplementedRoutineServiceServer) Stream(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRoutineServiceServer) mustEmbedUnimplementedRoutineServiceServer() {}
func (UnimplementedRoutineServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutineServiceServer will
// result in compilation errors.
type UnsafeRoutineServiceServer interface {
	mustEmbedUnimplementedRoutineServiceServer()
}

func RegisterRoutineServiceServer(s grpc.ServiceRegistrar, srv RoutineServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutineService_ServiceDesc, srv)
}

func _RoutineService_Req_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Frame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).Req(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_Req_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).Req(ctx, req.(*Frame))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoutineServiceServer).Stream(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoutineService_StreamServer = grpc.BidiStreamingServer[Frame, Frame]

// RoutineService_ServiceDesc is the grpc.ServiceDesc for RoutineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routine.RoutineService",
	HandlerType: (*RoutineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Req",
			Handler:    _RoutineService_Req_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RoutineService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "routine.proto",
}
