// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: routine.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_routine_proto protoreflect.FileDescriptor

const file_routine_proto_rawDesc = "" +
	"\n" +
	"\rroutine.proto\x12\aroutine\x1a\x1cgoogle/protobuf/struct.proto2\x89\x01\n" +
	"\x0eRoutineService\x127\n" +
	"\x03Req\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\x12>\n" +
	"\x06Stream\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct(\x010\x01B\x12Z\x10kernel/grpc;grpcb\x06proto3"

var file_routine_proto_goTypes = []any{
	(*structpb.Struct)(nil), // 0: google.protobuf.Struct
}
var file_routine_proto_depIdxs = []int32{
	0, // 0: routine.RoutineService.Req:input_type -> google.protobuf.Struct
	0, // 1: routine.RoutineService.Stream:input_type -> google.protobuf.Struct
	0, // 2: routine.RoutineService.Req:output_type -> google.protobuf.Struct
	0, // 3: routine.RoutineService.Stream:output_type -> google.protobuf.Struct
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routine_proto_init() }
func file_routine_proto_init() {
	if File_routine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routine_proto_rawDesc), len(file_routine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routine_proto_goTypes,
		DependencyIndexes: file_routine_proto_depIdxs,
	}.Build()
	File_routine_proto = out.File
	file_routine_proto_goTypes = nil
	file_routine_proto_depIdxs = nil
}
