# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'routine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rroutine.proto\x12\x07routine\"\x18\n\x05\x46rame\x12\x0f\n\x07payload\x18\x01 \x01(\t2e\n\x0eRoutineService\x12%\n\x03Req\x12\x0e.routine.Frame\x1a\x0e.routine.Frame\x12,\n\x06Stream\x12\x0e.routine.Frame\x1a\x0e.routine.Frame(\x01\x30\x01\x42\x12Z\x10kernel/grpc;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020kernel/grpc;grpc'
  _globals['_FRAME']._serialized_start=26
  _globals['_FRAME']._serialized_end=50
  _globals['_ROUTINESERVICE']._serialized_start=52
  _globals['_ROUTINESERVICE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
