# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import routine_pb2 as routine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in routine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutineServiceStub(object):
    """Frame -- wire 上唯一消息类型: payload = 完整事件消息的 JSON 文本
    (平铺 dict: {event, id, req_id, ...业务字段}, 事件字段面见 py 侧
    routine/protocol.py 的事件常量, proto 层不镜像字段----加事件零重生成).

    边界编解码: py json.dumps/loads (C 实现) / Go sonic(JIT) / rs
    serde_json, 各语言内部数据流(map/dict/Value)不变. 相比
    google.protobuf.Struct 少两层 Value 包装反射, wire 体积更小,
    且跨语言统一 JSON string 单一格式(kernel 对 payload 按需解析).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Req = channel.unary_unary(
                '/routine.RoutineService/Req',
                request_serializer=routine__pb2.Frame.SerializeToString,
                response_deserializer=routine__pb2.Frame.FromString,
                _registered_method=True)
        self.Stream = channel.stream_stream(
                '/routine.RoutineService/Stream',
                request_serializer=routine__pb2.Frame.SerializeToString,
                response_deserializer=routine__pb2.Frame.FromString,
                _registered_method=True)


class RoutineServiceServicer(object):
    """Frame -- wire 上唯一消息类型: payload = 完整事件消息的 JSON 文本
    (平铺 dict: {event, id, req_id, ...业务字段}, 事件字段面见 py 侧
    routine/protocol.py 的事件常量, proto 层不镜像字段----加事件零重生成).

    边界编解码: py json.dumps/loads (C 实现) / Go sonic(JIT) / rs
    serde_json, 各语言内部数据流(map/dict/Value)不变. 相比
    google.protobuf.Struct 少两层 Value 包装反射, wire 体积更小,
    且跨语言统一 JSON string 单一格式(kernel 对 payload 按需解析).
    """

    def Req(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Req': grpc.unary_unary_rpc_method_handler(
                    servicer.Req,
                    request_deserializer=routine__pb2.Frame.FromString,
                    response_serializer=routine__pb2.Frame.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=routine__pb2.Frame.FromString,
                    response_serializer=routine__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routine.RoutineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routine.RoutineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutineService(object):
    """Frame -- wire 上唯一消息类型: payload = 完整事件消息的 JSON 文本
    (平铺 dict: {event, id, req_id, ...业务字段}, 事件字段面见 py 侧
    routine/protocol.py 的事件常量, proto 层不镜像字段----加事件零重生成).

    边界编解码: py json.dumps/loads (C 实现) / Go sonic(JIT) / rs
    serde_json, 各语言内部数据流(map/dict/Value)不变. 相比
    google.protobuf.Struct 少两层 Value 包装反射, wire 体积更小,
    且跨语言统一 JSON string 单一格式(kernel 对 payload 按需解析).
    """

    @staticmethod
    def Req(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routine.RoutineService/Req',
            routine__pb2.Frame.SerializeToString,
            routine__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/routine.RoutineService/Stream',
            routine__pb2.Frame.SerializeToString,
            routine__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
